name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: true
    permissions:
      id-token: write
      contents: write

    outputs:
      released: ${{ steps.check_release.outputs.released }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Perform tasks
        if: steps.release.outputs.released == 'true'
        run: echo "Performing tasks after a new release"

  build-push-artifact:
    needs: release
    if: needs.release.outputs.released == 'true'
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: earthbook2
      REGION: asia-east1
      GAR_LOCATION: asia-east1-docker.pkg.dev/earthbook2/earthbook-docker-registry/earthbook/drone-remote-id
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: show VERSION
        run: |
          echo ${{ needs.release.outputs.version }}
          echo ${{ needs.release.outputs.tag }}
